apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: val-bt
  namespace: argocd
  annotations:
    # We'll use this for future GitOps once helm-charts are ready
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/0xPuncker/lab-tao.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: bittensor-testnet
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
